// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAASupiiPHUZqPJ0da2Mp9SaEc9ODlrAQ',
    appId: '1:34401454093:web:aa0beb7d6ba2ceab322d44',
    messagingSenderId: '34401454093',
    projectId: 'flutterriverpodtodoapp',
    authDomain: 'flutterriverpodtodoapp.firebaseapp.com',
    storageBucket: 'flutterriverpodtodoapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYhA0SUIdVV-Y6EE1NKlLGEyb3Oxck47w',
    appId: '1:34401454093:android:02ebeaf2c10095b1322d44',
    messagingSenderId: '34401454093',
    projectId: 'flutterriverpodtodoapp',
    storageBucket: 'flutterriverpodtodoapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsE-r7PvCsRnS_n6D7uWGDK6WpVdtq_Io',
    appId: '1:34401454093:ios:dacca0c0a2807183322d44',
    messagingSenderId: '34401454093',
    projectId: 'flutterriverpodtodoapp',
    storageBucket: 'flutterriverpodtodoapp.appspot.com',
    iosClientId: '34401454093-329p2irqmrphc2746i3jel88jgvtqj8l.apps.googleusercontent.com',
    iosBundleId: 'com.antoine.flutter',
  );
}
